In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [51]:
import numpy as np
np.__version__

'1.19.5'

In [19]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a
a[3:10]

array([ 4,  5,  6,  7,  8,  9, 10])

In [17]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[-5:]

array([ 6,  7,  8,  9, 10])

In [15]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

np.size(a,0)


4

In [14]:
np.ndim(a)

2

In [ ]:
np.empty([5,5])

In [ ]:
np.random.randint(5)

In [ ]:
np.random.rand(5,5)

In [ ]:
np.random.randint(5)

In [20]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [23]:
np_mix_matrix[1:3]

array([['three', '4'],
       ['five', '6']], dtype='<U5')

In [26]:
np.size(np_mix_matrix)


6

In [12]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np.array(np_mix_matrix[:,1])

array(['2', '4', '6'], dtype='<U5')

In [13]:

np_mix_matrix 

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [37]:
len(np_mix_matrix)

3

In [45]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
for i in range (0,len(np_mix_matrix)):
    print(np_mix_matrix[i] , end=' ')
    

['one' '2'] ['three' '4'] ['five' '6'] 

In [49]:
a = np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [51]:
c = np.full((2,2),10)
c

array([[10, 10],
       [10, 10]])

In [53]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
i = 0
while i < 5:
    print('yeah boy')
    i+=1

yeah boy
yeah boy
yeah boy
yeah boy
yeah boy


In [18]:
L = [[1,2,3],
     [4,5,6],
     [7,8,9]]
L
np.shape(L)

(3, 3)

In [17]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np.size(a)
np.shape(a)

(4, 3)

In [24]:
L = [[1,2,3],
     [4,5,6],
     [7,8,9]]
a = np.array(L)
L.reverse()
L

[[7, 8, 9], [4, 5, 6], [1, 2, 3]]

In [42]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

a[1,:]
a[:,-1]
np.shape(a)

(4, 3)

In [43]:
a[0:2,:] = 8
a

array([[ 8,  8,  8],
       [ 8,  8,  8],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
a.ndim

2

In [40]:
np.size(a,0)

4

In [44]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [47]:
np.array(np_mix_matrix[:,1], dtype = int)

array([2, 4, 6])

In [56]:
c = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
d = np.array([[5,1,2],[3,8,6],[7,9,7]])
np.matmul(c,d)  #คูณตามหลัก matrix 

array([[ 32,  44,  35],
       [ 77,  98,  80],
       [122, 152, 125],
       [167, 206, 170]])

In [68]:
round(np.random.rand()*10)

3

In [213]:
a = np.random.RandomState(0)
[a.randint(5) for item in range(10)]

[4, 0, 3, 3, 3, 1, 3, 2, 4, 0]

In [177]:
#EX 2
a= np.random.rand(10,5)
np.place(a[:,-1],a[:,-1]>0 , np.round(a[:,-1]))
a    



array([[0.75018871, 0.31494249, 0.81646071, 0.14752539, 0.        ],
       [0.39836203, 0.44848246, 0.74429149, 0.11782751, 0.        ],
       [0.74969076, 0.77216627, 0.03507367, 0.92713339, 0.        ],
       [0.17122526, 0.86954682, 0.3108755 , 0.28998995, 1.        ],
       [0.05704786, 0.75462259, 0.88139542, 0.07728666, 1.        ],
       [0.54171039, 0.73143341, 0.4073778 , 0.69194963, 1.        ],
       [0.6856476 , 0.71230262, 0.47691842, 0.67352938, 0.        ],
       [0.64035653, 0.56210547, 0.95893945, 0.2246235 , 1.        ],
       [0.69936808, 0.75245914, 0.70563883, 0.913276  , 1.        ],
       [0.4373692 , 0.79372265, 0.79733765, 0.14279871, 0.        ]])

In [178]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[0, 1, 2, 0, 1],
       [2, 0, 2, 2, 0],
       [0, 0, 2, 0, 1],
       [0, 0, 2, 2, 1],
       [1, 2, 2, 1, 2]])

In [183]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a
np_matrix = np.delete(a,[1,2],0)
np_matrix

array([[ 1,  2,  3],
       [10, 11, 12]])

In [198]:
#EX 3 ไม่ได้เพราะcolumn มีเเค่ 0 - 4
np_matrix = np.random.randint(11,size = (5,5))
np_matrix
idx = [1,2,3,4,5]
np_matrix[idx,:]

array([[8, 9, 6, 8, 9],
       [6, 5, 3, 5, 5],
       [7, 0, 6, 6, 3],
       [2, 8, 5, 6, 5]])

In [336]:
#EX 4 
a = np.random.randint(10, size=(10, 5))
b = np.random.randint(2, size=10)
dummy0 = np.zeros(shape=(10,5))
dummy1 = np.zeros(shape=(10,5))
row_arr = 0
row_lab = 0

for i in range(0,10,1):
    if b[row_lab] !=0 :
        np.place(dummy0[row_lab],a[row_arr]>0 , np.round(a[row_arr]))
        row_arr += 1
    else:
        np.place(dummy1[row_lab],a[row_arr]>0 , np.round(a[row_arr]))
        row_arr += 1
    row_lab += 1

dummy0 = dummy0[~np.all(dummy0 == 0, axis=1)]
dummy1 = dummy1[~np.all(dummy1 == 0, axis=1)]
print('Default Value = \n',a)
print('label Value =', b)
print('Label That value is 0 \n',dummy0 , '\n','Label That value is 1 \n',dummy1)








Default Value = 
 [[2 7 2 8 2]
 [0 0 7 9 8]
 [6 3 7 3 3]
 [5 4 4 7 7]
 [0 0 5 0 5]
 [6 1 9 9 1]
 [1 9 6 0 1]
 [9 9 1 5 4]
 [0 5 3 7 4]
 [0 5 9 2 1]]
label Value = [1 1 1 0 1 0 1 1 0 0]
Label That value is 0 
 [[2. 7. 2. 8. 2.]
 [0. 0. 0. 0. 7.]
 [6. 3. 7. 3. 3.]
 [1. 9. 6. 0. 0.]
 [9. 9. 1. 5. 4.]] 
 Label That value is 1 
 [[5. 4. 4. 7. 7.]
 [6. 1. 9. 9. 1.]
 [0. 0. 5. 3. 7.]
 [0. 0. 5. 9. 2.]]


array([10,  5])